version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:18"
      timezone: "UTC"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: ":arrow_up:"
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:18"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: ":arrow_up:"
